insert into exchange(exchange_name) values ('BakerySwap'),
                                           ('Gate.io'),
                                           ('0x Protocol'),
                                           ('WhiteBIT'),
                                           ('Osmosis'),
                                           ('ApeSwap'),
                                           ('Poloniex'),
                                           ('Upbit'),
                                           ('Bitstamp'),
                                           ('FTX Spot'),
                                           ('HitBTC'),
                                           ('Mdex (BSC)'),
                                           ('Gemini'),
                                           ('Binance Dex'),
                                           ('Binance'),
                                           ('CEX.IO'),
                                           ('Raydium'),
                                           ('SpookySwap'),
                                           ('Bybit Spot'),
                                           ('SushiSwap (BSC)'),
                                           ('Uniswap V2'),
                                           ('Bancor Network'),
                                           ('SushiSwap'),
                                           ('Pangolin'),
                                           ('OKX'),
                                           ('BitGlobal'),
                                           ('Coinsbit'),
                                           ('SunSwap'),
                                           ('Sushiswap (Polygon)'),
                                           ('Bitfinex'),
                                           ('SushiSwap (Arbitrum)'),
                                           ('BeamSwap'),
                                           ('Okcoin'),
                                           ('Pancake Swap'),
                                           ('Uniswap V3'),
                                           ('Tidex'),
                                           ('AscendEX'),
                                           ('EXMO'),
                                           ('Huobi Global'),
                                           ('1inch'),
                                           ('Kucoin'),
                                           ('Kraken'),
                                           ('MEXC'),
                                           ('BitMart'),
                                           ('Dodo (BSC)'),
                                           ('Solarbeam'),
                                           ('Bittrex'),
                                           ('Bitforex'),
                                           ('Kraken Pro'),
                                           ('Coingapp'),
                                           ('Mexc Global'),
                                           ('Coinbase'),('Coinbase Pro');